# Generated by Django 2.1.1 on 2018-12-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodels', '0003_jobs_summarized'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='chunks',
            field=models.IntegerField(default=0),
        ),
    ]
