# Generated by Django 2.1.1 on 2018-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodels', '0004_jobs_chunks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='chunks',
        ),
        migrations.AddField(
            model_name='jobs',
            name='accuracy',
            field=models.CharField(default='0.00', max_length=10),
        ),
    ]
