# Generated by Django 2.1.1 on 2018-11-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181108_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appusers',
            options={'verbose_name': 'App Users'},
        ),
    ]
