# Generated by Django 2.1.1 on 2018-11-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181108_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appusers',
            options={'verbose_name': ('App Users',), 'verbose_name_plural': 'App Users'},
        ),
    ]
