# Generated by Django 2.1.1 on 2018-11-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181108_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appusers',
            options={'verbose_name_plural': 'App Users'},
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='email',
        ),
        migrations.AddField(
            model_name='appusers',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
