# Generated by Django 2.1.1 on 2018-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181109_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
